use mercadokwanza;

select 'CLIENTE', count(*) from cliente UNION select 'ITEM_VENDA', count(*) from item_venda 
UNION SELECT 'LOJA', COUNT(*) FROM loja UNION SELECT 'PRODUTO', COUNT(*)  FROM PRODUTO 
UNION SELECT 'PROVINCIA', COUNT(*) FROM PROVINCIA UNION SELECT 'STOCK', COUNT(*) STOCK FROM STOCK
UNION SELECT 'VENDA', COUNT(*) FROM VENDA;  